// Names blacklist import script
const names = [
  "ACCHIARDI Jean Baptiste",
  "ACCOMANDO Gilles",
  "ACHER Juliette",
  "ACQUIER Helene",
  "ADAM Armelle",
  "AJASSE Michel",
  "ALBERT Laurence",
  "ALEGRE Jean",
  "ALLAIN Camille",
  "ALLAIN Hervé",
  "ALLENBACH Judith",
  "ALT Eric",
  "ALUZE Maxime",
  "ANDRE Louis",
  "ANSELMI Jean-Marc",
  "ANTONY DUCROT Daniele",
  "APAP Georges",
  "APETROAIE Cristina",
  "APRUZZESE Maria",
  "ARGIBAY Lucia",
  "ARMANDET Sylvie",
  "ARMANET Louis-Marie",
  "ARNAL Isabelle",
  "ARRIAL Blandine",
  "ASSAAD Caroline",
  "ASSOULINE Myriam",
  "ASSOUS Marianne",
  "AUBERTIN Nicolas",
  "AUDUGE Patrick",
  "AUGIER Florence",
  "AUVERGNON Lucie",
  "AYGALENQ Marielle",
  "AZEMA Céline",
  "BACH Nadine",
  "BAFFET Virgine",
  "BALAGUE Mathilde",
  "BALANCA VIGERAL Emmanuelle",
  "BALAYN Christian",
  "BALESTRERI Gina",
  "BALG Ariane",
  "BALLOT-DESPROGES Clothilde",
  "BALLU Philippe",
  "BALMAIN Henri",
  "BANDIERA Jean-Pierre",
  "BANIZETTE Benjamin",
  "BARANGER Thierry",
  "BARBAUD Laurence",
  "BARD Amélie",
  "BARDIAU Sophie",
  "BARDOU Marie-Camille",
  "BARDOUT Jean-Claude",
  "BARINCOU Paul",
  "BARON Hadrien",
  "BAROUKH Betty",
  "BARRAL Odile",
  "BARRIER Francoise",
  "BARRY Myriam",
  "BARTHE BOUGENAUX Dominique",
  "BARTOLOMEI FRANCOU Christine",
  "BARTOLOMEI Louis",
  "BASSELIN Véronique",
  "BASSET DETOLLE Annie",
  "BASTIEN RABNER Françoise",
  "BATALLA Sandrine",
  "BAUDOT Cécile",
  "BAYET Elise",
  "BEAUCHAMPS Nathalie",
  "BEAUGENDRE Charles",
  "BECLIER Florence",
  "BEGON BORDREUIL Laurence",
  "BELFORT Elisabeth",
  "BELGHAZI Agnès",
  "BELLEGO Olivier",
  "BELLOC Suzanne",
  "BELLON Laurence",
  "BELLOT Guillaume",
  "BELPERRON Jean-Philippe",
  "BEN HAMIDA Sophie",
  "BENAC Irene",
  "BENEDICTO Anita",
  "BENEIX BACHER Catherine",
  "BENETON Hervé",
  "BENHAMOU Yves",
  "BENHILAL Lémia",
  "BENMOHAMMED Yacine",
  "BERGER François",
  "BERGOUNIOU GOURNAY Nadia",
  "BERHAULT Alexandra",
  "BERKANE Soumya",
  "BERLIOZ Jean-Christophe",
  "BERLIOZ Jean-Claude",
  "BERNARD DE VEAUCE Charlotte",
  "BERNEZ Bruno",
  "BERNEZ Clotilde",
  "BERTETTO Céline",
  "BERTHET Camille",
  "BERTRAND Mathilde",
  "BERTRAND Nelly",
  "BESNARD Céline",
  "BEYLS François",
  "BIALE Alice",
  "BIDAL Mathieu",
  "BIDART Robert",
  "BIFFOT Chouchou",
  "BIGORIE Florence",
  "BIGOT BLOESS Josiane",
  "BIHAN Nicolas",
  "BILLAUD Alain",
  "BISIACH Alain",
  "BLANC Alain Louis",
  "BLANC Frédéric",
  "BLANC Nicolas",
  "BLANC Patrice",
  "BLANCHET Simon",
  "BLATMAN Michel",
  "BLATRY Joelle",
  "BLIER Elodie",
  "BLIN Jean-Marie",
  "BLIN Muriel",
  "BLISSON Laurence",
  "BLOCH Isabelle",
  "BLUME Sylvie",
  "BOCCIARELLI ANCEL Candide",
  "BOCCIARELLI ANCEL Eric",
  "BOISDRON Vincent",
  "BOISSINOT Agnes",
  "BONDUELLE Matthieu",
  "BONNOUVRIER Chloé",
  "BORDENAVE-MUSSO Chantal",
  "BORDO François",
  "BORREL ABENSUR Sylvie",
  "BORREL PERNOD Elisabeth",
  "BOSCHERON Adeline",
  "BOSSARD Béatrice",
  "BOTELLA Agnès",
  "BOUAFFASSA Myriam",
  "BOUCHER Jean-Pierre",
  "BOUCHON Jean-Michel",
  "BOUDET Alexandra",
  "BOUGUERRA Aurore",
  "BOUIX Sabrina",
  "BOUJON Dorian",
  "BOULANGER Paul Henri",
  "BOULNOIS Marie-Elisabeth",
  "BOURILLON Clémence",
  "BOURJADE Jean_Paul",
  "BOUSSO-SALL Sophie",
  "BOUTARD Marie-Claude",
  "BOUTET FAUVET Hélène",
  "BOUVIER Florence",
  "BOUVIER Isabelle",
  "BOUVIER Jean-Claude",
  "BOUVIER Odette Luce",
  "BOUVIER-LACROIX Nicolas",
  "BOUZIGE Stéphanie",
  "BRACQ Julie",
  "BRAULT Dominique",
  "BRESSOULALY FREDET Claudine",
  "BREUILLE Charlotte",
  "BRIAN-BARRANGUET Geneviève",
  "BRICOGNE Philippe",
  "BRION Célia",
  "BROCHE Erika",
  "BRUERE Karine",
  "BRUNIN Laëtitia",
  "BRUNNER Anne",
  "BRUNOT Coralie",
  "BRUSLON Anne",
  "BRUSTON Pascale",
  "BUNS JAKUSZ Cathy",
  "BUONO Agathe",
  "BUQUANT Melina",
  "BURESI Aude",
  "BURGUIERE Emilie",
  "Bonnet Laurent",
  "CABANES Angélique",
  "CABAT Christian",
  "CADEILLAN Sarah",
  "CAHOREAU Aline",
  "CAILLET Djamel",
  "CALAS Marie Bernadette",
  "CALES Fanny",
  "CALVET Marie-Cécile",
  "CAMPISTRON Christine",
  "CANO Vincent",
  "CARATTI Nadia",
  "CARBONNIER DEBU Irène",
  "CARLIER SZRAMA Sophie",
  "CARPENTIER Sébastien",
  "CARTOUX Lucie",
  "CASSAN FERRIER Patrick",
  "CASTEX Patrick",
  "CAUMONT Marie",
  "CAURIER-LEHOT Mireille",
  "CAVROIS BERNARD Marie-Luce",
  "CHABANEIX Sandrine",
  "CHAFAI Ida",
  "CHALBOS Eric",
  "CHALBOS GRESARD Anne Laurence",
  "CHALOPIN Alain",
  "CHAMBEL Adrien",
  "CHAMBERT Floriane",
  "CHAMPS Emilie",
  "CHARBONNIER Anaïs",
  "CHARDENOUX Simon",
  "CHARIGNON Anne-Laure",
  "CHARLIER Gaël",
  "CHARMOILLAUX Vincent",
  "CHARRON Aline",
  "CHARVIN Ambroise",
  "CHASLONS Pascal",
  "CHATAIGNER Corentin",
  "CHATEAU TAPSOBA Hélène",
  "CHAUCHIS Delphine",
  "CHAUFFAUT Delphine",
  "CHAULET Pauline",
  "CHAUMET Alexandra",
  "CHAUSSERIE LAPREE Denis",
  "CHAUVET Elisabeth",
  "CHEMAMA Alain",
  "CHEVALIER Delphine",
  "CHEVALLIER Laetitia",
  "CHEVRIER Patrick",
  "CHICLET Caroline",
  "CHIPAULT Lise",
  "CHIRCOP-MARRA Anaïs",
  "CHOUK Aïda",
  "CHUILON Isabelle",
  "CIROTTE Clémence",
  "CLARAC Eloïse",
  "CLARAMUNT Karine",
  "CLEVA Jean-Louis",
  "CLOUTEAU Léa",
  "CODOL FOUREL Christine",
  "COENEN Coralie",
  "COLLIOT Typhaine",
  "COMBES Sophie",
  "COMMEAU Cécile",
  "COMPAROT Juliette",
  "CONGOURDEAU Sophie",
  "CONSTANTIN Bastien",
  "COQUET Anne",
  "CORDARY Lorraine",
  "CORDIER Nadia",
  "CORNET Marie",
  "CORROY Adeline",
  "COTHIAS Eva",
  "COTTE Alice",
  "COUJARD MOREL Maud",
  "COURROYE Alain",
  "COUVIDAT Marion",
  "COUZIGOU Thierry",
  "CREBASSA Muriel",
  "CRENIER VAUDANO Anne",
  "CRENN RICCI Solène",
  "CRIQ Odile",
  "CROCHARD Caroline",
  "CROISSANDEAU Cécile",
  "CROUSSE Geneviève",
  "CUSEY Anne-Claire",
  "CUSSAC Alexia",
  "DAGHESTANI Candice",
  "DALE DELBECQUE Françoise",
  "DANGLA Matthieu",
  "DANGUY DES DESERTS Lara",
  "DAROLLE Bertrand",
  "DARWICHE Laura",
  "DAUDIN Alice",
  "DAVOINE Angèle",
  "DE CHARETTE Patrice",
  "DE FILIPPIS Livia",
  "DE MARICOURT Etienne",
  "DE MAXIMY AUBOURG Martine",
  "DE PAS David",
  "DEBERGUE Jeanne",
  "DEBU Jacques",
  "DEGARDIN Julie",
  "DEGLISE Jean",
  "DEJOURS Clara",
  "DEL VITTO Sarah",
  "DELAPORTE Félix",
  "DELAPORTE Lucie",
  "DELAZZARI Cécile",
  "DELBOS Vincent",
  "DELCAMBRE Gisèle",
  "DELEPIERRE MARAIS Martine",
  "DELGADO Roxanne",
  "DELORME Marie-Claire",
  "DELOUX Mathilde",
  "DELPEUCH Daniel",
  "DELSOL Mathieu",
  "DELY JARINSKI Hannelore",
  "DEMARTINI Pascale",
  "DEMAY Hélène",
  "DEPARIS Eric",
  "DESAUNETTES Frédéric",
  "DESBUREAUX PELAY Pascale",
  "DESCARD MAZABRAUD Marie-Paule",
  "DESCHAMPS Jean-Pierre",
  "DESCOT Nathalie",
  "DESCOUBES Benoit",
  "DESFAUDAIS Annie",
  "DESGENS Guillaume",
  "DESGOUIS Laurent",
  "DESGRANGES Arnaud",
  "DESGRANGES PLASSART Sophie",
  "DESJARDIN Sandra",
  "DESROCHES Ines",
  "DESVALOIS Emmanuelle",
  "DEVALLOIS Denis",
  "DIGNEAU Camille",
  "DIZIERE Annabelle",
  "DJAMAA Myriam",
  "DJEMNI-WAGNER Sonya",
  "DJIAN Stéphanie",
  "DOMINIQUE Nathalie",
  "DONAZ-PERNIER Morgan",
  "DOROY Fabienne",
  "DOUCET Ariane",
  "DOUNIOL Ariane",
  "DOUSTALY PIERRU Catherine",
  "DRAHI Veronique",
  "DROUIN Dorothée",
  "DRZAZGA Amélie",
  "DUBERNET Alice",
  "DUBOIS GOMBERT Dina",
  "DUBREUIL Katia",
  "DUCA Laurie",
  "DUCHAC Caroline",
  "DUCHAMPLECHEVAL Marion",
  "DUCHEMIN Stephane",
  "DUFAY Emmanuelle",
  "DUJARDIN Hubert",
  "DUNO Jacqueline",
  "DUPERRIER Dominique",
  "DUPUIS Delphine",
  "DURBECQ Sophie",
  "DUREUX Dimitri",
  "De Chalup Diane",
  "EGLIN Muriel",
  "EL ABDOULI Issam",
  "ELIZABETH Jessica",
  "ELLUL CURETTI Laëtitia",
  "ELLUL-CURETTI Laetitia",
  "ERHARDT Sandrine",
  "EVANGHELOU Morgane",
  "EXERTIER Francoise",
  "FABRE Emeline",
  "FAISSOLLE Jean",
  "FAIVRE Laurence",
  "FALLENOT Agnes",
  "FALLOT Daniel",
  "FANTAPIE Emmanuel",
  "FAUCONNIER Gabrielle",
  "FAURE Clara",
  "FAYAT Caroline",
  "FAYOL NOIRETERRE Jean-Marie",
  "FEBVRE MOCAER Marianne",
  "FENART Laëtitia",
  "FERGANE-TAUZY Julie",
  "FERRAGU Aurore",
  "FERRAND Julien",
  "FERRARI Héloïse",
  "FEVRIER Anne",
  "FIASELLA LE BRAS Fabienne",
  "FICARA Julien",
  "FILLIARD Pierre",
  "FIQUET Thibaut-Pierre",
  "FLAMIGNI Eva",
  "FLAYOU Assemaa",
  "FONTAINE Vincent",
  "FORST Déborah",
  "FOUASSE Jacques",
  "FOUCAUD LELU Sandra",
  "FOURCADE Claudine",
  "FULLA Anne",
  "FULLEDA Antonio",
  "GABINAUD Laure",
  "GABORIAU MONTHIOUX Simone",
  "GABORIAU Patrick",
  "GABRELLE Pascale",
  "GADRAT Xavier",
  "GALAND LERNER Sophie",
  "GALDIN Lesly",
  "GALLAND BOYER Claudine",
  "GALLEGO Yves",
  "GALLET Marie",
  "GALLOT-LE-GRAND Elodie",
  "GAND Pascal",
  "GARAT Séverine",
  "GARCIA PUECH Jeannie",
  "GARCIA Sylvie",
  "GARCIN Yves",
  "GARDIN Marion",
  "GARET Dominique",
  "GARNIER Patricia",
  "GARRIGUE PERESS Sonia",
  "GAUCHOTTE Valentine",
  "GAUDIN Emilie",
  "GAUVAIN-PUIGBERT Mathilde",
  "GAY Corinne",
  "GAZAN Max",
  "GENARD Damien",
  "GENDRE Emmanuelle",
  "GENDRE Patrick",
  "GEORGEAULT Andrée",
  "GERAUD-CHARVET Lise",
  "GERNIER Rozenn",
  "GERVILLIE Jean",
  "GESBERT Anne Marie",
  "GEST Juliette",
  "GILBERT Bénédicte",
  "GIMENO CABRERA Véronique",
  "GINOUX Myriam",
  "GIORDANI François",
  "GIRAUD Pierre",
  "GIROD Francine",
  "GLIMOIS Noémie",
  "GNEITING Margot",
  "GOANVIC Isabelle",
  "GOBIN HOMASSEL Anne-Marie",
  "GODARD Marie-Lucie",
  "GODELAIN Sandrine",
  "GOMES Nuno Miguel",
  "GONLE Roselyne",
  "GONNET Corentin",
  "GONZALEZ Patricia",
  "GORECKI David",
  "GORY Amandine",
  "GOURCEROL Flore",
  "GOUTINES Mylène",
  "GOUZENNE Pierre",
  "GOYET Marie",
  "GRAFFEO Giovanna",
  "GRANDE Clara",
  "GRANDFILS Raphael",
  "GRANDGEORGE Thomas",
  "GREGOIRE Julien",
  "GRIMAL Gallien",
  "GRIPP Florina",
  "GRIVELET Constance",
  "GROS Antoine",
  "GROS Félix",
  "GROSSER Isadora",
  "GRZESZCZAK Céline",
  "GUICHARD Charlotte",
  "GUICHARD François",
  "GUIGNARD Anne-Cécile",
  "GUILHEM DUCLEON Laura",
  "GUILLEMAUT Bernard",
  "GUILLOT Ghislaine",
  "GUILLOTTE Anaïs",
  "GUILLOUX Alice",
  "GUINARD Christine",
  "GURTNER Norbert",
  "GUTIERREZ Gilles",
  "Guillaume Efisens",
  "HAIRON Viviane",
  "HALGAND Joseph",
  "HARSON Kathleen",
  "HAYEM Jérôme",
  "HAZIZA Judith",
  "HEBRARD Charles",
  "HEDERER Jacques",
  "HEDRICH Marc",
  "HEINISCH François",
  "HEMMER Marianne",
  "HENAFF Maewenn",
  "HENON Charlotte",
  "HENRIOT Patrick",
  "HERAS DE PEDRO Sylvie",
  "HERAULT Josiane",
  "HERBO Clément",
  "HERNANDEZ Fabienne",
  "HEROUF Kevin",
  "HERZOG Agnès",
  "HEUMANN Sarah",
  "HEURTEBISE Laura",
  "HEYTE PIERRE Marie-Hélène",
  "HIGELIN Audrey",
  "HOANG-TRONG Léa",
  "HOEFLER GEMEHL Jasmine",
  "HOLOGNE PINTORE Catherine",
  "HORIOT Agathe",
  "HUDDE HAMROUNI Melanie",
  "HULAK Claire",
  "HUMBERT Olivier",
  "HUMEAU Laure",
  "HUNTER-FALCK Soleine",
  "HUREL Benoist",
  "IMERGLIK Helene",
  "IRAGNES Frédérique",
  "ISSAD Magali",
  "JACQMIN Côme",
  "JACQUELINE Clémence",
  "JACQUES Florence",
  "JAFFREZ Blandine",
  "JALLIFFIER-VERNE Léa",
  "JAOUEN Robert",
  "JAPPONT Frédéric",
  "JAQUET Coralie",
  "JARA Stéphanie",
  "JARNO Nicole",
  "JEAN Jean-Paul",
  "JEANNERET Serge",
  "JEANNIN DAUBIGNEY Philippe",
  "JEHIEL Dominique",
  "JIMENEZ Magali",
  "JOHNSTONE Elsa",
  "JOINET Louis",
  "JOLY Claude",
  "JOLY Gérard",
  "JOSEPH Thomas",
  "JOST Pierre",
  "JOULIN Ollivier",
  "JOURNIAC Mathilde",
  "JUBERT Garance",
  "JUILLARD Philippe",
  "JUNG Mégane",
  "JUNGMAN Benjamin",
  "Jolivet Brigitte",
  "KACER Jennyfer",
  "KBIDA Ekrame",
  "KESSOUS Roland",
  "KETTANI Marine",
  "KLAJNBERG Marcel",
  "KLEIN Guillaume",
  "KOSKAS Gwenaelle",
  "KOVALEVSKY Maxime",
  "KRETOWICZ Stéphanie",
  "KRETZ Véronique",
  "KRIEF-SEMITKO Catherine",
  "KUBICA Etienne",
  "KUHNMUNCH Caroline",
  "LABBE Véronique",
  "LABORDE BARBANEGRE Michèle",
  "LABORDE Delphine",
  "LACOSTE ETCHEVERRY Gracieuse",
  "LACOUR CHABAS Valérie",
  "LACROIX Camille",
  "LACROIX François Regis",
  "LAFAY Agnès",
  "LAFAYSSE Stéphanie",
  "LAFITE Elsa",
  "LAGAILLARDE Marion",
  "LAGARDE Sylvie",
  "LAGOUTTE QUENTIN FROIGNANT Louise",
  "LAGRAVE Emilie",
  "LAHAYE Stéphanie",
  "LAHL Astrid",
  "LAITHIER ROSENBERG Elise",
  "LAJOIE Colette",
  "LALANDE Sandrine",
  "LALOUBERE JOUGLA Myriam",
  "LAMAZE Mathilde",
  "LAMBERT Samra",
  "LANDAT Elodie",
  "LANDOT Bernard",
  "LANDOU Franck",
  "LANFREY Anaïs",
  "LANOES Clara",
  "LAPLANE Bruno",
  "LAPRAYE Françoise",
  "LAPRIE Anne-Marie",
  "LARDY Léa",
  "LARIDANT Baptiste",
  "LAROYENNE Aude",
  "LASSERRE Quitterie",
  "LASTERA GERHARDS HELENE NULL",
  "LATHELIER LOMBARD Catherine",
  "LAUNAY Jean",
  "LAUPENIE Roselyne",
  "LAURENT BERQUET Marie-Christine",
  "LAURENT Elsa",
  "LAURET Valerie",
  "LAURIER Lucile",
  "LAVIGERIE Clémentine",
  "LAZARE Sun Yung",
  "LE BERRE WURM Véronique",
  "LE COZ Elisabeth",
  "LE FRANCOIS GOUEE Catherine",
  "LE GUILLOU Raphaël",
  "LE MEUNIER Anne",
  "LE VERRE Marie",
  "LEAVER PIERSON Patricia",
  "LEBLANC Cendra",
  "LEBLANC Virgile",
  "LEBON BLANCHARD Marie-Françoise",
  "LEBOUCHER CABELGUENNE Emmanuelle",
  "LECARON HORNN JEANNE NULL",
  "LECHARNY Mona",
  "LECLAIR BRON Marie",
  "LECRUBIER Daniel",
  "LEDARD MOUTY Julie",
  "LEFAIX Sylvie",
  "LEFEBVRE Manon",
  "LEGRAND Dominique",
  "LEGRAND Sophie",
  "LEHMANN THOMAS Nicolle",
  "LEHOUX Elise",
  "LEJEUNE Cyril",
  "LEJEUNE Marie-Anna",
  "LEMAIRE Béatrice",
  "LEMERCIER Bertrand",
  "LEMOINE Cécile",
  "LEMONIER Vincent",
  "LENA Louise",
  "LENOIR Aurélie",
  "LEPEU Vanessa",
  "LEPINE Maud",
  "LEPRINCE Marie-Ange",
  "LEQUEUX BESSON Anne",
  "LERNOULD Christian",
  "LEROY GISSINGER Lise",
  "LEROY Marie-Christine",
  "LESCOFFIT BULLE Claudine",
  "LESPARRE Joëlle",
  "LESUEUR DE GIVRY Emmanuel",
  "LETEXIER Annabelle",
  "LETOMBE LUCIE",
  "LEVACHER Elodie",
  "LEVEQUE Karen",
  "LEVY Albert",
  "LIAUZU Isabelle",
  "LIBERGE Sylvie",
  "LIEBERHERR Marie",
  "LIMOU Lydie",
  "LIMOUSIN Clarisse",
  "LIMOUZA Lucien",
  "LINDEN Alexandre",
  "LIPIANSKY Manon",
  "LITAUDON Chantal",
  "LOGELIN Jacques",
  "LOISEAU Mathilde",
  "LORENTZ Stéphane",
  "LORENZI Stéphane",
  "LORIOT-LHOTELLERIE Christine",
  "LOSSON Gaspard",
  "LOUWERSE Isabelle",
  "LUDET Daniel",
  "LUMBROSO Sonia",
  "LUXARDO Mariella",
  "LYON-CAEN Pierre",
  "Louhibi Fouzia",
  "MADURAUD Anne Laure",
  "MAESTRACCI Nicole",
  "MAFFRE Anne",
  "MAIZA Anne-Sophie",
  "MALET Nathalie",
  "MALINOSKY Didier",
  "MALLAND Elise",
  "MALLET Jacques",
  "MANIE-SAMSON Romain",
  "MANOUVRIER Laëtitia",
  "MAO Philippe",
  "MARAND MICHON Marie-Jose",
  "MARCHAND Hubert",
  "MARFAING Pascale",
  "MARIE Mathilde",
  "MARIETTE Sabine",
  "MARMORAT Géraldine",
  "MAROT Pierre-Yves",
  "MARQUET Ségolène",
  "MARSHALL Didier",
  "MARTELLA Pierre",
  "MARTELLO Pierre",
  "MARTIN Audrey",
  "MARTIN Jean-Paul",
  "MARTIN-PLE Frédérique",
  "MARTIN-SOULON Hélène",
  "MARTINEL CHANSOU Agnès",
  "MARTINEZ Grégoire",
  "MARTINOT Pierre-François",
  "MARTRES Françoise",
  "MARY Stéphanie",
  "MAS Marie-Laure",
  "MASCARIN Valérie",
  "MASSELOT Marjorie",
  "MASSELOT SCHMIT Marjorie",
  "MASSEY Anne-Dominique",
  "MASSOUD Sarah",
  "MASSUET ep FAYE Marie-Christine",
  "MATHIEU Dominique",
  "MATTEI Sophie",
  "MAUGENDRE Fiona",
  "MAUGUIN Louise",
  "MAZARS LAGRANGE Marie-France",
  "MEGDOUD Aïcha",
  "MEHRABI Maryam",
  "MELGAR Catherine",
  "MENDI DIRAISON Isabelle",
  "MENGIN AMIGORENA Laurence",
  "MENOT Marion",
  "MENS BIGOURDAN Joelle",
  "MERCIER Corentin",
  "MERCIER Rachel",
  "MESLOT Jean-Patrick",
  "MEYER Aurélie",
  "MEZARD Anne",
  "MICHAUD Gilles",
  "MICHAUT Anna",
  "MICHEL ANGOT Laurence",
  "MICHELI Laure",
  "MIQUEL PRIBILE Sylvie",
  "MOCAER Joel",
  "MOLCO Karine",
  "MOLLARET Laurence",
  "MOLLAT FABIANI Sophie",
  "MONDINEU HEDERER Odile",
  "MONEREAU Jean-François",
  "MONNINI-MICHEL Anne",
  "MONPIERRE Evelyne",
  "MONSARRAT Nils",
  "MONTEIL Bertheline",
  "MONTFORT Pascal",
  "MONTPIED Claire",
  "MORA Elise",
  "MORALES Aude",
  "MORE Catherine",
  "MOREAU Jean Louis",
  "MOREAU Margaux",
  "MORICE VIGOR Anne Marie",
  "MORILLON Cécile",
  "MORNET Benoit",
  "MORVAN Antoine",
  "MOUCHARD Michel",
  "MOULIN THUAL Béatrice",
  "MOULIN Tania",
  "MOURAND Marion",
  "MOUSSA Alexandre",
  "MOUTON MICHAL Christine",
  "MOUTOUVIRIN Maliga",
  "MOUTY-TARDIEU Julie",
  "MPUTU-COBBAUT Maryse",
  "MSIKA Pierre",
  "MULLER Catherine",
  "MULLER HEYM Isabelle",
  "MUNOZ Albertine",
  "MURACCIOLE Marie- Josèphe",
  "MURCIANO Jean Pierre",
  "NASRI Sabri",
  "NAULEAU Bérengère",
  "NEDHIF Latifa",
  "NETTER Eva",
  "NEYMARC LOTROICQ Françoise",
  "NICOD Jean Claude",
  "NICOLAS Fabienne",
  "NICOLAY Alexandra",
  "NIRDE-DORAIL Régine",
  "NOCLAIN Véronique",
  "OBADIA Marjorie",
  "OBEIN Adrien",
  "OBREGO Nicole",
  "OLIVROT Gaelle",
  "OLLIER Franck",
  "OLLIVE Daniel",
  "ONGARO Eleonora",
  "OTT Jean-Philippe",
  "OTT Renée Michèle",
  "PAGES Nicolas",
  "PAJANACCI Véronique",
  "PALANQUE Bernard",
  "PALAU Alain",
  "PALMIER Sabrina",
  "PANTALACCI Carole",
  "PANTEL Perle",
  "PARAT Sophie",
  "PARIS Frédéric",
  "PARIS MULLER Gaelle",
  "PATOUX GUERBER Catherine",
  "PATTE Dominique",
  "PAUCHER Claire",
  "PAWLOWSKI FETET Anne-Sophie",
  "PECQUEUR Emilie",
  "PEJU Jean- Patrick",
  "PEKLY Valentine",
  "PELISSERO Pascale",
  "PENAUD Jean Jacques",
  "PERALTA Sandra",
  "PERREUX-NARDON Emmanuelle",
  "PERRIN Marie-Daphné",
  "PERSONNIC Tiphaine",
  "PERSYN Benoît",
  "PETIAUD Anais",
  "PETIT Amandine",
  "PETIT Aurélien",
  "PETIT Baudoin",
  "PETIT Emeline",
  "PETITJEAN Emilie",
  "PETREAULT Martine",
  "PETROVSKI Emilie",
  "PEYRACHE Christine",
  "PEYROU Sabine",
  "PEZZATTI Raymond",
  "PHAURE Maryse",
  "PHILIPPE Émilie",
  "PHILIPS Nahema",
  "PIAT Ariane",
  "PIBAROT Sarah",
  "PIC Juliette",
  "PICAL Daniel",
  "PICARDAT Béatrice",
  "PICART Stéphanie",
  "PICHARD Adeline",
  "PICHOT GAUDINO Marie Hélène",
  "PIERRE Benjamin",
  "PIERRE Bernard",
  "PIET Anne",
  "PILON Sandrine",
  "PINET Béatrice",
  "PINET Joan",
  "PINSARD Juliane",
  "PIROTTE Carole",
  "PITE Veronique",
  "PITON Murielle",
  "POELEMANS Clorinda",
  "POIRIER Aurélie",
  "POIRIER CHAUX Anne Marie",
  "POIZAT Liselotte",
  "PONCET Aude",
  "PONCET Isabelle",
  "PONS Laetitia",
  "PORTELLI Serge",
  "POSILEK Nathalie",
  "POTASZKIN Tatiana",
  "POTTIER Pauline",
  "POUGHON Robert",
  "POULAIN Claire",
  "POUPON-JOYEUX Célestine",
  "POUS Fabienne",
  "POUSIN Elise",
  "PROBST Justine",
  "PROUST Emmanuelle",
  "PUGET-FLESCH François-Xavier",
  "PUIG Anne",
  "PUPION Laura",
  "QUANTIN Agnes",
  "QUIAU Léa",
  "QUINTALLET Claire",
  "QUINTANE Emilie",
  "RAFFIN Michelle",
  "RAMET Carole",
  "RAMON Catherine",
  "RAPILLY Eve",
  "RASTEGAR PRAX Francine",
  "RATEAU Natacha",
  "RATIE Jean Paul",
  "RAVALLEC Yves",
  "RAYNAUD Elisabeth",
  "REBEYROTTE Jacqueline",
  "REBOULOT Michel",
  "REGNIER Justine",
  "REGNIER Marie Blanche",
  "REMY Stephane",
  "RENARD Muriel",
  "RENARD Nathalie",
  "RENAULT Juliette",
  "RENOU Annie",
  "REUFLET Kim",
  "REY ANDERSON Fabienne",
  "RIANDEY Paul",
  "RICHARD Diane",
  "RICHARD Emmanuelle",
  "RICHAUD Julien",
  "RIEU Pablo",
  "RIEUX Jean Pierre",
  "RIGAL Arthur",
  "RIGAL Etienne",
  "RIGOLLOT Geraldine",
  "RIMBAULT Christine",
  "RIUNE Vincent",
  "ROBERT Anne-Marie",
  "ROBERT Sarah",
  "ROBIN Benedicte",
  "ROBIN Lucie",
  "ROBINET Bruno",
  "ROCHARD Emmanuel",
  "ROCHE Nathalie",
  "ROCHE Noemie",
  "RODRIGUES Sophie",
  "RODRIGUEZ Daniel",
  "ROGER Francois",
  "ROGER Nicole",
  "ROGNIAUX Anne",
  "ROLLAND Yves",
  "ROMDHANE Hanène",
  "ROME Isabelle",
  "ROMINGER Alexandra",
  "ROMME Guy",
  "RONIN Marie",
  "ROQUES Serge",
  "ROS Martine",
  "ROSENZWEIG Anne",
  "ROSTAND JONES Christine",
  "ROUCHY PORAS Noellie",
  "ROUCOU Denis",
  "ROUET Lucille",
  "ROUILLARD Julie",
  "ROULIN Christelle",
  "ROUSSEAU Benoît",
  "ROUSSEAU Valérie",
  "ROUSSEL Guillaume",
  "ROUSSELLE Cyrielle",
  "ROUSTAING CONCHON Hélène",
  "ROUSTEAU LARRE Sylvie",
  "ROUX Philippine",
  "RUBIO Nathalie",
  "RUINART DE BRIMONT Emilie",
  "SABATIER Laurent",
  "SAFAR Celine",
  "SAFATIAN Saliha",
  "SAGANT Valerie",
  "SAGE REMY NULL",
  "SAINATI Gilles",
  "SAINSILY-PINEAU Sandrine",
  "SAINT MARTIN Laura",
  "SAINT RAMON Helene",
  "SAINT-BLANCARD Marie-Pierre",
  "SALAS Denis",
  "SALIOU Isabelle",
  "SALLEE Chloé",
  "SAMII Mandana",
  "SANCHEZ Madeleine",
  "SAUVAGE Guillaume",
  "SCELLE Benedicte",
  "SCHAFFHAUSER Dominique",
  "SCHALCHLI Ulrich",
  "SCHALLER Fabienne",
  "SCHAMBER Gerard",
  "SCHAPIRA Antoine",
  "SCHMEITZKY LHUILLERY Marie Laure",
  "SCHNEIDER Philippe",
  "SCHOULER Clément",
  "SEBAN Emmanuelle",
  "SEGALEN Ariane",
  "SEGAUD Zoé",
  "SEGOND Myriam",
  "SEGUINET Margot",
  "SEITE Mickael",
  "SEJOURNET Méline",
  "SERVANT Elsa",
  "SERVONNAT BRUEL Marie Germaine",
  "SEURIN Isabelle",
  "SEZER Mathilde",
  "SIBUE Brigitte",
  "SIEBERT Julia",
  "SIGALA Hélène",
  "SILVY-LELIGOIS Raphaëlle",
  "SIMBILLE Marie",
  "SIMON-KOLLER Camille",
  "SIMONOT Solene",
  "SIRE-MARIN Evelyne",
  "SIVAGER Sandy",
  "SIZAIRE Vincent",
  "SMIDEREN Nina",
  "SOLE Laëtitia",
  "SOLLY Claire",
  "SOMAVILLA Anne",
  "SOMME Catherine",
  "SOMMER Jean Michel",
  "SOMMERER Marc",
  "SOUBEYRAN Philippe",
  "SOUBEYRAN Thibaud",
  "SOULAS Camille",
  "SOULE Olivier",
  "SOUMMER Ilham",
  "SPERY Christophe",
  "SPIRLET MARCHAL Virginie",
  "SPRIET Thibaut",
  "STAGNARA LACROIX Marie",
  "STENGEL Christine",
  "STRUNK Corinne",
  "SULTAN COLOMBAT Catherine",
  "SUPLY Sylvie",
  "SUQUET BOYER Michèle",
  "SUQUET Henri",
  "SUREL Gaël",
  "SYSKA Céline",
  "SZEWCZYK Florent",
  "SZKLARZ Katia",
  "Simon Paul",
  "TABARDEL Paméla",
  "TACITE Nadège",
  "TAILLANDIER Catherine",
  "TAILLEBOT Bernard",
  "TANGUY Chloe",
  "TAPIN LAMOUREUX Agnès",
  "TARDY PISARRA Anne",
  "TARON Clarisse",
  "TERNOY Manon",
  "TERRIER Marie",
  "TEZE Anne",
  "THEPAUT Claire",
  "THEVENET Marie",
  "THIBAULT CARRAU Anne-Marie",
  "THIBAULT ROMAN AMAT Cécile",
  "THIBAULT Stephane",
  "THOMAS Armelle",
  "THOMAS Jean Luc",
  "THONIER Sylvain",
  "THUBIN Emilie",
  "TILLIE Samuel",
  "TILMONT Virginie",
  "TISSOT Camille",
  "TIZON Hélène",
  "TLEMSANI Amaria",
  "TONDEUX Ludivine",
  "TOUATI Nina",
  "TOULOUSE Elisabeth",
  "TOUR André",
  "TOURET DE COUCY Francois",
  "TRAFI Audrey",
  "TRICOCHE Isabelle",
  "TRIDON Vincent",
  "TROMBI Doriane",
  "TROUSSARD Marie",
  "TRUBUILT Anaïs",
  "TRUCHE Sylvie",
  "TUFFREAU Sophie",
  "VAILHE Judith",
  "VALENSI Sophie",
  "VALENTE Aurélie",
  "VALETTE Christine",
  "VAN LINDEN Clara",
  "VAN RUYMBEKE Lisa",
  "VANDERMAESEN Benoit",
  "VANDERMAESEN Lola",
  "VANNIER Catherine",
  "VANNIER Marie-Christine",
  "VASSAIL Muriel",
  "VAULOT PFISTER Jean Christian",
  "VAURY Sonia",
  "VAUZELLE FAUVET Sylvie",
  "VENNETIER LEBRETON Veronique Anne",
  "VERDIER Alice",
  "VERDIER Céline",
  "VERDINI-SIMON Caroline",
  "VERGNE Alice",
  "VERMEULEN Hélène",
  "VERNHET HEINRICH Béatrice",
  "VERNIER Vincent",
  "VERPEAUX Jean Louis",
  "VIDALIE Jean-Baptiste",
  "VIDALINC Emma",
  "VIEILLEVILLE Pascal",
  "VIETTE Elsa",
  "VIGNY Juliette",
  "VIGUIER Céline",
  "VIGUIER Yoann",
  "VILAMOT Maëliss",
  "VILLE MOZE Marie Hélène",
  "VILLETTE Jean Francois",
  "VILTINGOT Jacques",
  "VINAS-ROUDIERES Myrtis",
  "VIRGINIO Marie-Charlotte",
  "VITRAC Aurélien",
  "VOGELWEITH Alain",
  "VOLLAIRE LOMBARD Helene",
  "VRAIN Anais",
  "VULLO Giovanni",
  "WAECHTER BRUGIDOU Florence",
  "WAECHTER Bruno",
  "WALLACH Anne Sophie",
  "WALTER Isabelle",
  "WASTL Elisabeth",
  "WENDLING Francois",
  "WICKHAM Guillaume",
  "WINTER Stéphane",
  "WOLF Aude",
  "XUEREB Didier",
  "YOU Didier",
  "ZAVARO Maurice",
  "ZERRI Anaïs",
  "ZISSMANN Agnes",
  "ZMIROU Jean François",
  "ZOUAOUI Karima",
  "ZYLBERBERG Mathilde",
  "guillaume test2",
];

const docs = names.map(name => ({
  name: name,
  reason: "Support blacklist",
  createdAt: new Date(),
  createdBy: "support"
}));

const batchSize = 100;
let inserted = 0;
let skipped = 0;

for (let i = 0; i < docs.length; i += batchSize) {
  const batch = docs.slice(i, i + batchSize);
  try {
    const result = db.blacklist.insertMany(batch, { ordered: false });
    inserted += Object.keys(result.insertedIds).length;
    print(`Batch ${Math.floor(i/batchSize) + 1}: inserted ${Object.keys(result.insertedIds).length}`);
  } catch (e) {
    if (e.insertedIds) {
      inserted += Object.keys(e.insertedIds).length;
      skipped += batch.length - Object.keys(e.insertedIds).length;
      print(`Batch ${Math.floor(i/batchSize) + 1}: inserted ${Object.keys(e.insertedIds).length}, skipped ${batch.length - Object.keys(e.insertedIds).length}`);
    }
  }
}

print(`\nDone! Inserted: ${inserted}, Skipped: ${skipped}`);
print(`Total in blacklist: ${db.blacklist.countDocuments()}`);
